---
- hosts: tomcat
  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /java-app/target/hello-world-1.war
        dest: /apache-tomcat-9.0.85/webapps/hello-world-1.war
        remote_src: yes
      become: yes

